volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  mlops:
    name: mlops
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
    - published: 5050
      target: 80
    restart: always
  postgres:
    command:
    - postgres
    - -c
    - max_connections=150
    volumes:
    - ./mlflow/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER || exit 1
      timeout: 2s
    image: postgres:latest
    ports:
    - 127.0.0.1:5432:5432/tcp
    restart: always
  minio:
    restart: always
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    command: server --console-address ":9001" /data
  mlflow:
    restart: always
    build: ./mlflow
    container_name: mlflow_server
    depends_on:
        - minio
        - postgres
    ports:
        - "5001:5000"
    environment:
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: >
      bash -c "mlflow server --backend-store-uri postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/mlflow --default-artifact-root s3://mlflow/ --host 0.0.0.0
      && mlflow db upgrade postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/mlflow"
  fastapi:
    restart: always
    build: ./fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    container_name: fastapi
    depends_on:
        - mlflow
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - MLFLOW_TRACKING_URI=http://mlflow:5000
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - 8000:8000
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000


version: '1.3'
