apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: prefect
  labels:
    app: prefect-agent
spec:
  selector:
    matchLabels:
      app: prefect-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: agent
        image: prefect
        command: ["prefect", "agent", "start", "-q", "test"]
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PREFECT_API_URL
            valueFrom:
              secretKeyRef:
                name: prefect
                key: PREFECT_API_URL
          - name: PREFECT_API_KEY
            valueFrom:
              secretKeyRef:
                name: prefect
                key: PREFECT_API_KEY
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prefect
  name: prefect-agent
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-role-binding
  namespace: prefect
subjects:
- kind: ServiceAccount
  name: default
  namespace: prefect
roleRef:
  kind: Role
  name: prefect-agent
  apiGroup: rbac.authorization.k8s.io
