version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s: %(asctime)s.%(msecs)03d | %(message)s"
        datefmt: "%H:%M:%S"
# filters:
    # Define any custom filters to drops records containing
    # sensitive information
    # my_filter:
        # class: your_module.FilterClass
handlers:
    # The handlers we define here will output all logs they receieve by default
    # but we include the `level` so it can be overridden by environment
    console:
        level: 0
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        interval: 7
        filename: logfile.log
        formatter: simple
# The root logger: any logger without propagation disabled sends to here as well
root:
    # By default, we display warning level logs from any library in the console
    # to match Python's default behavior while formatting logs nicely
    level: INFO
    handlers: [console,file]